### ISSUE TITLE
What is the advantage of using ci-publish?

### ISSUE THREAD

**Issue by gunar** [bahmutov/ci-publish#6]
Hi Gleb! I had a similar thought last week, and ended up setting up [auto-publishing manually](https://github.com/invisible-tech/avow/commit/db510ddfffa399b61582d822bdd1319e224d6923).

In what ways is your implementation better than mine?

Thanks in advance.

**Comment by bahmutov** [comment]
Use https://github.com/semantic-release/semantic-release or https://github.com/bahmutov/semantic-action - these things do publish only if there are semantic commits (like `feat(foo): add new cool feature foo`) since last publish. They also can check conditions (like CI, Node version, run tests before publishing, check if you are going to break dependent projects), and will publish post release notes even notifying everyone who opened an issue that is now resolved, see https://github.com/bahmutov/github-post-release

You will get a much better workflow if you just let semantic-release manage this for you. I wrote `ci-publish` because semantic-release did not like CircleCI for example :)

**Comment by gunar** [comment]
Great answer. Thank you very much.
